"""add_floorplans

Revision ID: 8e52727b8b8e
Revises: 7ba2cfc3f8d3
Create Date: 2026-06-02 09:23:33.917160
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8e52727b8b8e'
down_revision: Union[str, None] = '7ba2cfc3f8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('real_width_mm', sa.Float(), nullable=True),
    sa.Column('real_height_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_anchors',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('floor_plan_id', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=True),
    sa.Column('polygon_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_anchors')
    op.drop_table('floor_plans')
    # ### end Alembic commands ###
